const bioList = [
    {
        name: "Human",
        helpText: "",
        levelMod: 0,
        official: true,
        con: 0,
        str: 0,
        dex: 0,
        wis: 0,
        int: 0,
        cha: 0,
      },
      {
        name: "Elf",
        helpText: "+2 Dex / -2 Con / Lowlight Vision",
        levelMod: 0,
        official: true,
        con: -2,
        str: 0,
        dex: 2,
        wis: 0,
        int: 0,
        cha: 0,
      },
      {
        name: "Orc",
        helpText: "",
        levelMod: 0,
        official: true,
        con: 0,
        str: 0,
        dex: 0,
        wis: 0,
        int: 0,
        cha: 0,
      },
      {
        name: "Gnome",
        helpText: "",
        levelMod: 0,
        official: true,
        con: 2,
        str: -2,
        dex: 0,
        wis: 0,
        int: 0,
        cha: 0,
      },
      {
        name: "Dragonkin",
        helpText: "+8 Str / +2 Con / +2 Dex / +4 Wis / +2 Cha",
        levelMod: 2,
        official: true,
        con: 2,
        str: 8,
        dex: 2,
        wis: 4,
        int: 0,
        cha: 2,
      },
      {
        name: "Warforged",
        helpText: "",
        levelMod: 0,
        official: true,
        con: 0,
        str: 0,
        dex: 0,
        wis: 0,
        int: 0,
        cha: 0,
      },
]